apiVersion: v1
kind: Secret
metadata:
  name: sifdronesecret
type: Opaque
data:
  dronesecret: {{ .Values.drone.secret | b64enc }}
  githubclient: {{ .Values.github.client | b64enc }}
  githubsecret: {{ .Values.github.secret | b64enc }}
