apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "drone-vol-claim"
  labels:
    heritage: drone
  annotations:
  {{ if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{ else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
