apiVersion: v1
kind: Service
metadata:
  name: drone-server
  labels:
    provider: drone-server
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30000
  selector:
    name: drone-server
  type: NodePort
